name: SmartrUI CLI Tests
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          node-version-file: '.nvmrc'  # Specify the Node.js version file

      - run: npm i
      - run: npm run build

      - name: Running SmartUI CLI Tests
        run: |
          npm i -g @lambdatest/smartui-cli
          smartui capture url.json --config smartui-web.json
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
